# Generated by Django 4.2.13 on 2025-11-06 08:23

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', fernet_fields.fields.EncryptedTextField(max_length=255)),
                ('session_data', fernet_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted JSON string of instagrapi settings', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'ordering': ['-updated_at'],
            },
        ),
    ]
